version: '2'
volumes:
  bundle:
services:
  app:
    image: ruby:2.5.1
    volumes:
      - .:/app
      - bundle:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    working_dir: /app
    command: bundle exec rspec
    ports:
      - '3000:3000'
    depends_on:
      - dynamodb

  dynamodb:
    image: ryanratcliff/dynamodb:latest
    ports:
      - 8000
