version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws:ro
    command: bundle exec rspec
    ports:
      - '3000:3000'
    depends_on:
      - dynamodb
  dynamodb:
    image: ryanratcliff/dynamodb:latest
    ports:
      - 8000
