version: '2'
services:
  app:
    image: 979514658570.dkr.ecr.eu-west-1.amazonaws.com/mes-base-image:0.24
    volumes:
      - .:/app
      - .bundle:/bundle
    command: bundle exec rspec
    ports:
      - '3000:3000'
    depends_on:
      - dynamodb

  dynamodb:
    image: ryanratcliff/dynamodb:latest
    ports:
      - 8000
