test: &minimum
  mes-access-tokens:
    read_capacity_units: 1
    write_capacity_units: 1
    indices:
      deactivated_at_index:
        read_capacity_units: 1
        write_capacity_units: 1
      tenant_id_index:
        read_capacity_units: 1
        write_capacity_units: 1

  mes-email-tokens:
    read_capacity_units: 1
    write_capacity_units: 1
    indices:
      used_at_index:
        read_capacity_units: 1
        write_capacity_units: 1

  mes-playlists:
    read_capacity_units: 1
    write_capacity_units: 1
    indices:
      deleted_at_index:
        read_capacity_units: 1
        write_capacity_units: 1
      tenant_id_index:
        read_capacity_units: 1
        write_capacity_units: 1
      parent_id_index:
        read_capacity_units: 1
        write_capacity_units: 1

  lte-original-resources:
    read_capacity_units: 1
    write_capacity_units: 1
    indices:
      period_created_at_index:
        read_capacity_units: 1
        write_capacity_units: 1
      content_id_index:
        read_capacity_units: 1
        write_capacity_units: 1

  lte-transformed-resources:
    read_capacity_units: 1
    write_capacity_units: 1
    indices:
      content_id_index:
        read_capacity_units: 1
        write_capacity_units: 1

  mes-contact-requests:
    read_capacity_units: 1
    write_capacity_units: 1

development:
  <<: *minimum

qa: &medium
  mes-access-tokens:
    read_capacity_units: 10
    write_capacity_units: 10
    indices:
      deactivated_at_index:
        read_capacity_units: 10
        write_capacity_units: 10
      tenant_id_index:
        read_capacity_units: 10
        write_capacity_units: 10

  mes-email-tokens:
    read_capacity_units: 1
    write_capacity_units: 1
    indices:
      used_at_index:
        read_capacity_units: 1
        write_capacity_units: 1

  mes-playlists:
    read_capacity_units: 5
    write_capacity_units: 2
    indices:
      deleted_at_index:
        read_capacity_units: 5
        write_capacity_units: 2
      tenant_id_index:
        read_capacity_units: 5
        write_capacity_units: 2
      parent_id_index:
        read_capacity_units: 5
        write_capacity_units: 2

  lte-original-resources:
    read_capacity_units: 10
    write_capacity_units: 10
    indices:
      period_created_at_index:
        read_capacity_units: 10
        write_capacity_units: 10
      content_id_index:
        read_capacity_units: 10
        write_capacity_units: 10

  lte-transformed-resources:
    read_capacity_units: 10
    write_capacity_units: 10
    indices:
      content_id_index:
        read_capacity_units: 10
        write_capacity_units: 10

  mes-contact-requests:
    read_capacity_units: 3
    write_capacity_units: 3

staging:
  <<: *medium

prod: &maximum
  mes-access-tokens:
    read_capacity_units: 80
    write_capacity_units: 10
    indices:
      deactivated_at_index:
        read_capacity_units: 80
        write_capacity_units: 10
      tenant_id_index:
        read_capacity_units: 80
        write_capacity_units: 10

  mes-email-tokens:
    read_capacity_units: 5
    write_capacity_units: 5
    indices:
      used_at_index:
        read_capacity_units: 5
        write_capacity_units: 5

  mes-playlists:
    read_capacity_units: 80
    write_capacity_units: 20
    indices:
      deleted_at_index:
        read_capacity_units: 80
        write_capacity_units: 20
      tenant_id_index:
        read_capacity_units: 80
        write_capacity_units: 20
      parent_id_index:
        read_capacity_units: 80
        write_capacity_units: 20

  lte-original-resources:
    read_capacity_units: 80
    write_capacity_units: 80
    indices:
      period_created_at_index:
        read_capacity_units: 80
        write_capacity_units: 80
      content_id_index:
        read_capacity_units: 80
        write_capacity_units: 80

  lte-transformed-resources:
    read_capacity_units: 80
    write_capacity_units: 80
    indices:
      content_id_index:
        read_capacity_units: 80
        write_capacity_units: 80

  mes-contact-requests:
    read_capacity_units: 5
    write_capacity_units: 5
